# Cloud Foundry Java Buildpack
# Copyright (c) 2013 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Configuration for WeightBalancingMemoryHeuristic.
#
# Each weighting is a decimal fraction between 0 and 1 and is used, except in the case of 'native', to calculate the
# corresponding default memory size. The sum of the weightings must not exceed 1.
---
heap: 0.5
permgen: 0.3
stack: 0.1
native: 0.1
